<?php
session_start();
date_default_timezone_set('America/Indiana/Indianapolis');

if (!isset($_SESSION['emp_id']) || $_SESSION['role'] !== 'driver') {
    die("Unauthorized.");
}

if (!isset($_GET['sid']) || empty($_GET['sid'])) {
    die("Error: No Shipment ID provided.");
}

$sid = $_GET['sid'];

$conn = new mysqli("mydb.itap.purdue.edu", "g1154084", "Group1!", "g1154084");
if ($conn->connect_error) {
    die("DB connection failed: " . $conn->connect_error);
}

// Same query as your main page, but NO pagination limitations
$sql = "SELECT DISTINCT 
            lce.EventTime, 
            lce.EmployeeID, 
            e.Role, 
            CONCAT(
                CASE lce.FromLocation
                    WHEN 'Zone' THEN CONCAT('Zone ', lce.FromZoneCode, ', ', lce.FromWarehouseID)
                    WHEN 'Vehicle' THEN lce.FromVehicleID
                    WHEN 'Clinic' THEN CONCAT('Clinic ', lce.FromClinicID)
                    ELSE 'Unknown Origin'
                END,
                ' &rarr; ',
                CASE lce.ToLocation
                    WHEN 'Zone' THEN CONCAT('Zone ', lce.ToZoneCode, ', ', lce.ToWarehouseID)
                    WHEN 'Vehicle' THEN lce.ToVehicleID
                    WHEN 'Clinic' THEN CONCAT('Clinic ', lce.ToClinicID)
                    ELSE 'Unknown Destination'
                END
            ) AS Movement, 
            lce.ConditionConfirmed AS ConditionStatus
         FROM LotCustodyEvent lce
         JOIN ShipmentLot sl ON lce.VendorID = sl.VendorID AND lce.BatchNumber = sl.BatchNumber AND lce.LotSeq = sl.LotSeq
         JOIN Employee e ON lce.EmployeeID = e.EmployeeID
         WHERE sl.ShipmentID = ?
         ORDER BY lce.EventTime ASC";

$stmt = $conn->prepare($sql);
$events = array();

if ($stmt) {
    $stmt->bind_param("s", $sid);
    $stmt->execute();
    $stmt->bind_result($t_time, $t_emp, $t_role, $t_move, $t_cond);   
    while ($stmt->fetch()) {
        $events[] = array(
            'time' => $t_time,
            'emp' => $t_emp,
            'role' => $t_role,
            'move' => $t_move,
            'cond' => $t_cond
        );
    }
    $stmt->close();
}
$conn->close();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chain of Custody - <?php echo htmlspecialchars($sid); ?></title>
    <style>
        /* Printer-friendly CSS styling */
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #000;
            background: #fff;
            padding: 20px;
        }
        h2, h3 { color: #000; margin-bottom: 5px; }
        .meta-info {
            color: #555;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 2px solid #000;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ccc;
        }
        th {
            font-weight: bold;
            border-bottom: 2px solid #000;
            background-color: #f9f9f9;
        }
        .cond-damaged { color: #d32f2f; font-weight: bold; }
        
        /* Hides URL paths and buttons from showing up on the printed PDF */
        @media print {
            @page { margin: 1cm; }
            body { padding: 0; }
            .no-print { display: none !important; }
        }
    </style>
</head>
<body onload="window.print()">

    <h2>PharmaCool Chain of Custody Report</h2>
    <div class="meta-info">
        <strong>Shipment ID:</strong> <?php echo htmlspecialchars($sid); ?><br>
        <strong>Report Generated:</strong> <?php echo date('M d, Y - H:i:s'); ?><br>
        <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['emp_id']); ?>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date & Time</th>
                <th>Person (Role)</th>
                <th>Movement</th>
                <th>Condition</th>
            </tr>
        </thead>
        <tbody>
            <?php if(!empty($events)): ?>
                <?php foreach($events as $event): ?>
                    <tr>
                        <td><?php echo date('M d, Y - H:i:s', strtotime($event['time'])); ?></td>
                        <td><?php echo htmlspecialchars($event['emp'] . " (" . $event['role'] . ")"); ?></td>
                        <td><?php echo $event['move']; ?></td>
                        <td>
                            <?php 
                                $cond_class = ($event['cond'] === 'Packaging Damaged') ? 'cond-damaged' : '';
                                echo "<span class='{$cond_class}'>" . htmlspecialchars($event['cond']) . "</span>";
                            ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else: ?>
                <tr>
                    <td colspan="4" style="text-align: center;">No chain of custody events recorded.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

    <div class="no-print" style="margin-top: 30px; text-align: center;">
        <button onclick="window.close()" style="padding: 10px 20px; cursor: pointer;">Close Window</button>
    </div>

</body>
</html>